apiVersion: v1
kind: Service
metadata:
  name: snaptrude-svc
  namespace: snaptrude
spec:
  selector:
    app: snaptrude-js-app
  ports:
    - name: snaptrude-port
      protocol: TCP
      port: 6041
      targetPort: snaptrude-port